---
title: "DGE_pattern"
output: html_document
date: "2025-12-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


maSigPro analysis for gene expression patterns clusterization
Package installation
```{r}

# if (!require("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# 
# BiocManager::install("maSigPro")

```



Complete maSigPro pipeline for regeneration timecourse, including normalized counts and design csv files in the local/resources folder
```{r}
library(maSigPro)

Input <- "resources/normcounts.u126.csv" #Matrix containing ID and cpm per timepoint 
data.mat <- read.csv(Input,header = TRUE, sep = ",",row.names = 1)
data.mat <- data.mat[,1:30]
data.mat <- 2^data.mat #transform logarithmic counts to linear counts per million
Input <- "resources/design.u126.csv" #File with treatment and replicates information
design.mat <- read.table(Input, header = TRUE, sep = ",", row.names = 1)

design <- make.design.matrix(design.mat, degree = 3) #change degrees according to number of time points

#FILTER STEP: filter out influential genes from matrix SKIP in the first round
data.mat$ID <- rownames(data.mat)
data.mat <- data.mat[!(data.mat$ID %in% search.vector),]
data.mat$ID <- NULL

#Find genes that change their expression level significantly across the time course
fit <- p.vector(data.mat, design, counts = TRUE, theta = 10, Q = 0.05, MT.adjust = "BH")
fit$i

#Find significant variables for each gene
tstep <- T.fit(fit, step.method = "backward", alfa = 0.05)

search.vector <- colnames(tstep$influ.info) #Go back to FILTER STEP

#Obtain list of significan genes
sigs <- get.siggenes(tstep, rsq = 0.80, vars = "groups") #R-squared may be adjusted to modulate pattern consistency vs number of signifcant genes
sigs$sig.genes$ALPvsControl$g

#
pdf("clusters.u126.pdf", width = 8, height = 8)
p <- see.genes(sigs$sig.genes$U0126vsControl, show.fit = F, dis =design$dis,
    cluster.method="hclust" ,cluster.data = 1, k.mclust = TRUE)

dev.off()

clusters <- as.data.frame(names(p$cut))
clusters$group <- as.numeric(p$cut) 
colnames(clusters) <- c("ID","cluster.mSP")

annotations <- read.csv("HVAEP1_annotation.csv", header = TRUE, sep = ",")

cluster.list <- merge(clusters, annotations, by = "ID")
write.csv(cluster.list, file = "cluster.list.80.csv")

```
